
[ClassVersion("1.0.0.0"), FriendlyName("xWaitForItem")]
class xWaitForItem : OMI_BaseResource
{
    [Key, Description("The path to the file or folder")] String Path;
    [Required, Description("The type of the target item"), ValueMap{"Directory","File"}, Values{"Directory","File"}] String Type;
    [Write, Description("The exact file length as implemented by System.IO.FileInfo")] Uint64 Length;
    [Write, Description("The minimum file length as implemented by System.IO.FileInfo")] Uint64 MinimumLength;
    [Write, Description("The minimum child item count including all files and folders")] Uint64 MinimumChildItemCount;
    [Write, Description("Retry count")] Uint32 RetryCount;
    [Write, Description("Retry interval in seconds")] Uint32 RetryInterval;
    [Write, Description("Ensure"), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;
};
